document.writeln("<meta charset=\'UTF-8\'>");
document.writeln("        <title>脚部</title>");
document.writeln("        <link rel=\'stylesheet\' href=\'/front/yynews/css/style.css\'>");
document.writeln("        <link rel=\'stylesheet\' href=\'/front/yynews/css/bottom.css\'>");
document.writeln("        <script type=\'text/javascript\' src=\'/front/script/jquery.min.js\'></script>");
document.writeln("    ");
document.writeln("    ");
document.writeln("         <!-- 以下为footer -->");
document.writeln("        <div class=\'footerbg\'>");
document.writeln("            <div class=\'ewm\'>");
document.writeln("                <img src=\'/front/yynews/images/ewm.jpg\'>");
document.writeln("                <p>微信关注，鹰眼新闻</p>");
document.writeln("            </div>");
document.writeln("           <div class=\'footer\'>");
document.writeln("              <div class=\'footer-center\'>");
document.writeln("                  <p class=\'smallnav\'>");
document.writeln("                     <a href=\'#\'>关于我们</a>");
document.writeln("                     <a href=\'#\'>加入我们</a>");
document.writeln("                     <a href=\'#\'>联系我们</a>");
document.writeln("                     <a href=\'#\'>广告服务</a>");
document.writeln("                     <a href=\'#\'>版权声明</a>");
document.writeln("                     <a href=\'#\'>友情链接</a>");
document.writeln("                  </p>");
document.writeln("                  <p class=\'copyrightnum\'>鄂ICP备17027254号-4</p>");
document.writeln("                  <p class=\'copyrightdate\'>版权所有©2017-2018 鹰眼新闻保留一切权利</p>");
document.writeln("              </div>");
document.writeln("           </div>");
document.writeln("        </div>");
document.writeln("       ");
document.writeln("    ");
document.writeln("");
document.writeln("");
document.writeln("<script>");
document.writeln("    $(\'.copyrightdate\').html(\'版权所有&copy2017\'+\'-\'+ new Date().getFullYear()+\' 鹰眼新闻保留一切权利\');");
document.writeln("</script>");