document.writeln("");
document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head lang=\'en\'>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <title>鹰眼新闻</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'/front/yynews/css/style.css\'/>");
document.writeln("    <link rel=\'stylesheet\' href=\'/front/yynews/css/top.css\'>");
document.writeln("    <script src=\'/front/script/jquery.min.js\'></script>");
document.writeln("    <script>");
document.writeln("        var websiteId = 3;");
document.writeln("    </script>");
document.writeln("    <script type=\'text/javascript\' src=\'/front/script/common.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'/front/yynews/script/js/top.js\'></script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<!-- 以下为头部 -->");
document.writeln("<div class=\'headerbg\'>");
document.writeln("    <div class=\'header\'>");
document.writeln("        <a href=\'/index.html\' id=\'homepage\'>");
document.writeln("            <img src=\'/front/yynews/images/logo.png\'/>");
document.writeln("        </a>");
document.writeln("        <ul class=\'nav\'>");
document.writeln("				<li><a href=\'/4/4.html?id=4\'  target=\'_blank\'>原创</a></li>");
document.writeln("				<li><a href=\'/6/6.html?id=6\'  target=\'_blank\'>房产</a></li>");
document.writeln("				<li><a href=\'/8/8.html?id=8\'  target=\'_blank\'>财经</a></li>");
document.writeln("				<li><a href=\'/3/3.html?id=3\'  target=\'_blank\'>互联网</a></li>");
document.writeln("				<li><a href=\'/10/10.html?id=10\'  target=\'_blank\'>文史</a></li>");
document.writeln("				<li><a href=\'/2/2.html?id=2\'  target=\'_blank\'>体育</a></li>");
document.writeln("        </ul>");
document.writeln("        <div class=\'header-right\'>");
document.writeln("            <div class=\'header-right-l\'>");
document.writeln("                <form>");
document.writeln("                    <input type=\'text\' name=\'search\' placeholder=\'搜索\'/>");
document.writeln("                    <a href=\'/front/yynews/ftl/search.html?id=3\'><img src=\'/front/yynews/images/search.png\' id=\'search\'/></a>");
document.writeln("                </form>");
document.writeln("            </div>");
document.writeln("            <div class=\'header-right-r\'>");
document.writeln("                <a><img src=\'/front/yynews/images/ren.png\' class=\'userAvatar\'/></a>");
document.writeln("                <p id=\'logoutBtn\' style=\'padding-top:5px;\'>退出登录</p>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\'blank\'></div>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
document.writeln(" ");
document.writeln("");