
document.writeln("");
document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("    <head lang=\'en\'>");
document.writeln("        <meta charset=\'UTF-8\'>");
document.writeln("        <title>右侧</title>");
document.writeln("        <link rel=\'stylesheet\' href=\'/front/yynews/css/style.css\'/>");
document.writeln("        <link rel=\'stylesheet\' href=\'/front/yynews/css/index.css\'>");
document.writeln("        <link rel=\'stylesheet\' type=\'text/css\' href=\'/front/yynews/css/contentright.css\'/>");
document.writeln("        <script type=\'text/javascript\' src=\'/front/script/jquery.min.js\'></script>");
document.writeln("           <script>");
document.writeln("        var websiteId = 3;");
document.writeln("        </script>");
document.writeln("        <script type=\'text/javascript\' src=\'/front/script/common.js\'></script>");
document.writeln("        <script type=\'text/javascript\' src=\'/front/yynews/script/js/right.js\'></script>");
document.writeln("    </head>");
document.writeln("    <body>");
document.writeln(" 			<input id=\'channelId\' type=\'hidden\' value=\'4\'>");
document.writeln("<div style=\'float: right\'>");
document.writeln("          <div class=\'content-right-center\' style='float:right'>");
document.writeln("               <!-- <h2>鹰眼视角 <span><a href=\'/front/yynews/ftl/more.html?id=3&channelId=4\' id=\'Original\'>更多...</a></span></h2>-->");
document.writeln("               <h2>鹰眼视角 <span><a target=\'_blank\' href=\'/4/4.html?id=4\' id=\'Original\'>更多...</a></span></h2>");
document.writeln("      	 			<div class=\'imgnewlist\'>");
document.writeln("      	 				<a target=\'_blank\' href=\'/4/2018-03-12/1135.html\'>");
document.writeln("                        <img src=\'http://source.yingyannews.com/news/top/1520840941694\' onload=\'drawImage(this,314,156)\'/>");
document.writeln("                        <p class=\'textone\'>");
document.writeln("							姜洋：券商增强竞争力要靠高质量发展");
document.writeln("                        </p>");
document.writeln("                        <p class=\'texttwo\'>");
document.writeln("                        	e公司讯，全国政协委员、证监会副主席姜洋在经济组讨论会后接受证券时报记者采访时表示，券商要做好中介，首先要对其（行为）负责；第二，券商要增强竞争力，肯定也要高质量发展。");
document.writeln("                        </p></a>");
document.writeln("                	</div>");
document.writeln(" 			");
document.writeln(" 			");
document.writeln(" 			");
document.writeln(" 			");
document.writeln(" 			");
document.writeln(" 			");
document.writeln("            ");
document.writeln("             <!--新闻列表-->");
document.writeln(" 				<ul class=\'rightnewlist\'>");
document.writeln(" 			");
document.writeln("                    <li><a target=\'_blank\' href=\'/4/2018-03-12/1120.html\'>姜洋：券商增强竞争力要靠高质量发展</a></li>");
document.writeln("                    <li><a target=\'_blank\' href=\'/4/2018-03-12/1027.html\'>台“统派”不满台独泼油漆 向台独谢顶人士喷生发剂</a></li>");
document.writeln("                    <li><a target=\'_blank\' href=\'/4/2018-03-05/298.html\'>《三块广告牌》口碑高排片偏低 “零差评”艺术片依旧难赢高票房</a></li>");
document.writeln("                    <li><a target=\'_blank\' href=\'/4/2018-03-05/305.html\'>科比动画短片获奥斯卡奖 飞侠捧小金人迎第二春</a></li>");
document.writeln("                    <li><a target=\'_blank\' href=\'/4/2018-03-05/297.html\'>科比动画短片获奥斯卡奖 飞侠捧小金人迎第二春</a></li>");
document.writeln("		");
document.writeln("                </ul>");
document.writeln("                ");
document.writeln("          </div>");
document.writeln("          <div class=\'content-right-bottom\' style='float:right;'>");
document.writeln("               <h2>热门文章</h2>");
document.writeln("              ");
document.writeln(" 					<div class=\'textpicBox\'>");
document.writeln("                  <img src=\'/front/yynews/images/top1.png\' class=\'smallimg\'/>");
document.writeln("                  <a target=\'_blank\' href=\'/4/2018-03-05/306.html\'><img src=\'http://source.yingyannews.com/news/top/1520234077130\' class=\'bigimg\' onload=\'drawImage(this,350,222)\'/></a>");
document.writeln("                  <div class=\'bg\'>");
document.writeln("                      <a target=\'_blank\' href=\'/4/2018-03-05/306.html\' style=\'color: #fff;\'><p>特技摩托系列新作 《城市游乐场》将登陆Switch</p></a>");
document.writeln("                  </div>");
document.writeln("               </div>");
document.writeln("     			");
document.writeln("          </div>");
document.writeln("");
document.writeln("</div>");
document.writeln("    </body>");
document.writeln("");
document.writeln("</html>");
document.writeln("");