document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head lang=\'en\'>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <title>头部</title>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'../css/top.css\'/>");
document.writeln("");
document.writeln("    <script type=\'text/javascript\' src=\'../../script/jquery.min.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'../../script/common.js\'></script>");
document.writeln("    <script src=\'../script/js/top.js\'></script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\'headerbg\'>");
document.writeln("    <div class=\'header\'>");
document.writeln("        <a href=\'index.html\'><img class=\'logo\' src=\'../images/logo.png\'/></a>");
document.writeln("        <div class=\'header-r\'>");
document.writeln("            <form>");
document.writeln("                <input type=\'text\' name=\'search\'/>");
document.writeln("                <img src=\'../images/search.png\' id=\'search\'/>");
document.writeln("            </form>");
document.writeln("        </div>");
document.writeln("        <div class=\'header_nav\'>");
document.writeln("            <ul class=\'nav\'>");
document.writeln("                <li><a href=\'nav.html\'>首页</a></li>");
document.writeln("                <li><a href=\'detail.html\'>财经</a></li>");
document.writeln("                <li><a href=\'\'>文化</a></li>");
document.writeln("                <li><a href=\'\'>政治</a></li>");
document.writeln("                <li><a href=\'\'>体育</a></li>");
document.writeln("                <li><a href=\'\'>娱乐</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
/*html转换js文件*/